name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    # runs-on: ubuntu-latest
    runs-on: mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World Script
        run: echo "Hello, World!"
