name: DAST LLM Code Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-scan-dast:
    runs-on: [self-hosted, Linux, X64, zap]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB }}
    steps:
      - name: Checkout current repo (target)
        uses: actions/checkout@v3
      - name: llm
        run: |
          python3 Zap-scan.py
          command=(f'cat dast_report.txt')
          os.system(command)
